#!/usr/bin/env python3
"""
Smart AI Detection with Word Boundaries + Context
==================================================
Uses word boundaries (\b) and contextual keywords to detect AI mentions
while filtering out false positives like person names.

Strategy:
1. Word boundaries ensure we match "Claude" not "Claudette" or "McClaudia"
2. Context patterns require nearby keywords like "generated", "assisted", "using"
3. Combine with known signatures (aider:, @anthropic.com, etc.)
4. Extract examples for manual verification
"""

import gzip
import json
import re
from pathlib import Path
from collections import defaultdict

DATA_DIR = Path("/Users/ilanstrauss/github-analysis/data/raw")

# =============================================================================
# AI TOOL NAMES (with word boundaries)
# =============================================================================
AI_TOOLS = [
    "Claude",
    "Copilot",
    "ChatGPT",
    "GPT-4",
    "GPT-3",
    "GPT4",
    "Cursor",
    "Aider",
    "Codeium",
    "CodeWhisperer",
    "Tabnine",
    "Gemini",
    "Bard",
]

# =============================================================================
# CONTEXT PATTERNS - words that indicate AI usage (not just mention)
# =============================================================================
CONTEXT_WORDS = [
    r"generated",
    r"assisted",
    r"helped",
    r"using",
    r"with\s+help",
    r"via",
    r"by",
    r"from",
    r"created\s+by",
    r"written\s+by",
    r"made\s+with",
    r"powered\s+by",
    r"Co-authored-by",
    r"co-author",
]

# =============================================================================
# BUILD SMART PATTERNS
# =============================================================================

def build_patterns():
    """Build regex patterns for AI detection."""
    patterns = {}

    # 1. STRICT SIGNATURES (highest confidence)
    patterns["signature_aider"] = re.compile(r"^aider:", re.MULTILINE | re.IGNORECASE)
    patterns["signature_anthropic"] = re.compile(r"@anthropic\.com", re.IGNORECASE)
    patterns["signature_coauthor_ai"] = re.compile(
        r"Co-authored-by:\s*(Claude|ChatGPT|GPT|Copilot|Gemini|Cursor)\s*<",
        re.IGNORECASE
    )

    # 2. CONTEXTUAL MENTIONS (AI tool + context word nearby)
    # Pattern: context_word ... AI_tool OR AI_tool ... context_word (within ~50 chars)
    for tool in AI_TOOLS:
        # Forward: "generated by Claude", "using Copilot", etc.
        pattern_fwd = re.compile(
            rf"(?:{('|').join(CONTEXT_WORDS)})\s+\b{tool}\b",
            re.IGNORECASE
        )
        patterns[f"context_{tool.lower()}_fwd"] = pattern_fwd

        # Backward: "Claude generated", "Copilot assisted", etc.
        pattern_bwd = re.compile(
            rf"\b{tool}\b\s+(?:generated|assisted|helped|created)",
            re.IGNORECASE
        )
        patterns[f"context_{tool.lower()}_bwd"] = pattern_bwd

    # 3. EXPLICIT AI MENTIONS
    patterns["explicit_ai_generated"] = re.compile(
        r"\b(AI[- ]generated|AI[- ]assisted|AI[- ]powered|LLM[- ]generated)\b",
        re.IGNORECASE
    )

    # 4. TOOL-SPECIFIC MARKERS
    patterns["aider_chat"] = re.compile(r"# Aider chat conversation:", re.IGNORECASE)
    patterns["cursor_sh"] = re.compile(r"\bcursor\.sh\b", re.IGNORECASE)

    return patterns

# =============================================================================
# FALSE POSITIVE FILTERS
# =============================================================================

FALSE_POSITIVE_PATTERNS = [
    # Person names: "Claude Smith", "Claude J.", "By Claude M."
    re.compile(r"Claude\s+[A-Z][a-z]+(?:\s|$|<)", re.IGNORECASE),
    re.compile(r"Claude\s+[A-Z]\.(?:\s|$|<)", re.IGNORECASE),
    # Company domains
    re.compile(r"copilot\.llc|copilot\.com(?!puter)", re.IGNORECASE),
    # OpenAI employee emails (not AI)
    re.compile(r"@openai\.com", re.IGNORECASE),
    # Repo/project names that happen to contain AI tool names
    re.compile(r"github\.com/[^/]+/[^/]*(?:claude|copilot|cursor)[^/]*(?:\s|$)", re.IGNORECASE),
]

def is_false_positive(msg: str) -> bool:
    """Check if message matches false positive patterns."""
    for fp in FALSE_POSITIVE_PATTERNS:
        if fp.search(msg):
            # Double-check: if it also has a strong AI signal, keep it
            if re.search(r"@anthropic\.com|^aider:|AI[- ]generated", msg, re.IGNORECASE | re.MULTILINE):
                return False
            return True
    return False


def extract_ai_mentions(year: int, max_examples: int = 30):
    """Extract AI mentions with smart patterns."""

    patterns = build_patterns()
    year_files = sorted(DATA_DIR.glob(f"{year}-*.json.gz"))

    if not year_files:
        print(f"No files found for {year}")
        return {}

    # Store matches and counts
    matches = defaultdict(list)
    counts = defaultdict(int)

    for fpath in year_files:
        print(f"Processing {fpath.name}...")

        try:
            with gzip.open(fpath, 'rt', encoding='utf-8', errors='replace') as f:
                for line in f:
                    try:
                        event = json.loads(line)
                        if event.get("type") != "PushEvent":
                            continue

                        actor = event.get("actor", {}).get("login", "unknown")
                        repo = event.get("repo", {}).get("name", "unknown")

                        for commit in event.get("payload", {}).get("commits", []):
                            if not commit.get("distinct", False):
                                continue

                            msg = commit.get("message", "")
                            if not msg or len(msg) < 5:
                                continue

                            # Check each pattern
                            for pattern_name, pattern in patterns.items():
                                if pattern.search(msg):
                                    # Skip false positives
                                    if is_false_positive(msg):
                                        continue

                                    counts[pattern_name] += 1

                                    if len(matches[pattern_name]) < max_examples:
                                        matches[pattern_name].append({
                                            "actor": actor,
                                            "repo": repo,
                                            "sha": commit.get("sha", "")[:8],
                                            "message": msg[:400],
                                            "file": fpath.name,
                                        })
                                    break  # Count commit only once

                    except json.JSONDecodeError:
                        continue
        except Exception as e:
            print(f"Error: {e}")
            continue

    return {"matches": dict(matches), "counts": dict(counts)}


def print_examples_for_review(results: dict):
    """Print examples in a format easy to manually review."""

    print("\n" + "=" * 70)
    print("MANUAL REVIEW: AI COMMIT EXAMPLES")
    print("Mark each as: ✓ (real AI) or ✗ (false positive)")
    print("=" * 70)

    # Group by category
    categories = {
        "SIGNATURES (high confidence)": [k for k in results["matches"].keys() if k.startswith("signature")],
        "CONTEXTUAL (medium confidence)": [k for k in results["matches"].keys() if k.startswith("context")],
        "EXPLICIT AI MARKERS": [k for k in results["matches"].keys() if k.startswith("explicit")],
        "TOOL-SPECIFIC": [k for k in results["matches"].keys() if k.startswith("aider") or k.startswith("cursor")],
    }

    for category, pattern_names in categories.items():
        relevant = [(p, results["matches"].get(p, [])) for p in pattern_names if results["matches"].get(p)]
        if not relevant:
            continue

        print(f"\n{'='*70}")
        print(f"  {category}")
        print(f"{'='*70}")

        for pattern_name, examples in relevant:
            count = results["counts"].get(pattern_name, 0)
            print(f"\n--- {pattern_name}: {count} total matches ---\n")

            for i, ex in enumerate(examples[:5], 1):
                print(f"[{i}] Actor: {ex['actor']}")
                print(f"    Repo:  {ex['repo']}")
                # Clean up message for display
                msg_clean = ex['message'].replace('\n', ' | ')[:250]
                print(f"    Msg:   {msg_clean}...")
                print(f"    [ ] Real AI  [ ] False Positive")
                print()


if __name__ == "__main__":
    print("=" * 70)
    print("SMART AI DETECTION WITH WORD BOUNDARIES + CONTEXT")
    print("=" * 70)

    # Run on 2024 data
    results = extract_ai_mentions(2024, max_examples=10)

    # Print summary
    print("\n" + "=" * 70)
    print("SUMMARY: PATTERN MATCH COUNTS")
    print("=" * 70)

    total = 0
    for pattern, count in sorted(results["counts"].items(), key=lambda x: -x[1]):
        if count > 0:
            print(f"  {pattern:40s}: {count:5d}")
            total += count

    print("-" * 50)
    print(f"  {'TOTAL':40s}: {total:5d}")

    # Print examples for manual review
    print_examples_for_review(results)

    # Save results for review
    import json as json_mod
    output_path = Path("/Users/ilanstrauss/github-analysis/output/ai_detection_review.json")
    with open(output_path, 'w') as f:
        json_mod.dump(results, f, indent=2, default=str)
    print(f"\n>>> Full results saved to: {output_path}")
